# Base environment, should contain Jupyter plugins and what not
name: notebook

channels:
  - conda-forge
  - nodefaults

dependencies:
  - nb_conda_kernels
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  - python=3.10
  - nbgitpuller
